### ISSUE TITLE
Support text-object motions

### ISSUE THREAD

**Issue by bromanko** [godbout/kindaVim.docs#97] opened 2022-07-21 21:37 UTC
This includes `(` and `)` to move sentences and `{` and `}` to move paragraphs.

**Comment by godbout** [comment] 2022-07-22 04:03
Sir Brian! welcome back 😄️

> This includes `(` and `)` to move sentences

yes, those ones are not done yet. what do you need exactly? motion in Normal Mode? motion in Visual Mode? yank/change/delete? (they're all individual moves that have to be implemented and tested separately.)

> and `{` and `}` to move paragraphs.

this one is already implemented (although not the count). see below:

https://user-images.githubusercontent.com/121373/180359849-8ead2569-1c59-443a-866a-813dda74d90a.mp4

but that of course requires the text to be readable, in order to pin the double linefeeds. any chance you're using the motion on an app where the text is not readable? app in the Key Mapping/911 Families?
also this motion follows Vim, and stops at double linefeeds. i.e. empty lines. not blank lines (that contain one or more whitespaces, and zero or one linefeed).

let me know!

**Comment by bromanko** [comment] 2022-07-23 05:35
> yes, those ones are not done yet. what do you need exactly? motion in Normal Mode? motion in Visual Mode? yank/change/delete? (they're all individual moves that have to be implemented and tested separately.)

Normal mode for me. Just used to quickly move around prior to an edit. 

You are right about paragraph motions. I might have been in Chrome when I tried which is definitely not the best supported app. I tend to avoid it. Worked fine in IaWriter.

**Comment by godbout** [comment] 2022-07-23 18:39
> Normal mode for me. Just used to quickly move around prior to an edit.

👌🏼️

> You are right about paragraph motions. I might have been in Chrome when I tried which is definitely not the best supported app. I tend to avoid it. Worked fine in IaWriter.

yes, currently i (The Wizard) recommends Brave and Chrome to be put in the Key Mapping Family due to a bug in Chromium that crept in around v98.

it's been reported here in May (just took the chance to ping them again now): https://bugs.chromium.org/p/chromium/issues/detail?id=1325643

and it's being followed by kV here: https://github.com/godbout/kindaVim.docs/issues/72

hopefully they fix their shits and we can put that back in PG-R. will be much better.

**Comment by godbout** [comment] 2022-07-26 14:39
(Chromium but for the AX may be fixed later in 107 latest: https://bugs.chromium.org/p/chromium/issues/detail?id=1325643)

**Comment by godbout** [comment] 2022-07-30 05:14
@bromanko checking the `()` now. it's a bit more complicated than expected, of course!:

```
A [sentence](dfile:///Users/guill/Library/Application%20Support/Dash/DocSets/Vim/Vim.docset/Contents/Resources/Documents/motion.html#sentence) is defined [as](dfile:///Users/guill/Library/Application%20Support/Dash/DocSets/Vim/Vim.docset/Contents/Resources/Documents/motion.html#as) ending at a '[.](dfile:///Users/guill/Library/Application%20Support/Dash/DocSets/Vim/Vim.docset/Contents/Resources/Documents/repeat.html#.)', '[!](dfile:///Users/guill/Library/Application%20Support/Dash/DocSets/Vim/Vim.docset/Contents/Resources/Documents/change.html#!)' or '[?](dfile:///Users/guill/Library/Application%20Support/Dash/DocSets/Vim/Vim.docset/Contents/Resources/Documents/pattern.html#?)' followed by either the
end of a line, or by a space or [tab](dfile:///Users/guill/Library/Application%20Support/Dash/DocSets/Vim/Vim.docset/Contents/Resources/Documents/intro.html#tab).  Any number of closing '[)](dfile:///Users/guill/Library/Application%20Support/Dash/DocSets/Vim/Vim.docset/Contents/Resources/Documents/motion.html#))', '[]](dfile:///Users/guill/Library/Application%20Support/Dash/DocSets/Vim/Vim.docset/Contents/Resources/Documents/index.html#])['](dfile:///Users/guill/Library/Application%20Support/Dash/DocSets/Vim/Vim.docset/Contents/Resources/Documents/motion.html#'), '"''
and ''' characters may appear after the '[.](dfile:///Users/guill/Library/Application%20Support/Dash/DocSets/Vim/Vim.docset/Contents/Resources/Documents/repeat.html#.)', '[!](dfile:///Users/guill/Library/Application%20Support/Dash/DocSets/Vim/Vim.docset/Contents/Resources/Documents/change.html#!)' or '[?](dfile:///Users/guill/Library/Application%20Support/Dash/DocSets/Vim/Vim.docset/Contents/Resources/Documents/pattern.html#?)' before the spaces,
tabs or end of line.  A [paragraph](dfile:///Users/guill/Library/Application%20Support/Dash/DocSets/Vim/Vim.docset/Contents/Resources/Documents/motion.html#paragraph) and section boundary is also a [sentence](dfile:///Users/guill/Library/Application%20Support/Dash/DocSets/Vim/Vim.docset/Contents/Resources/Documents/motion.html#sentence)
boundary.
If the '[J](dfile:///Users/guill/Library/Application%20Support/Dash/DocSets/Vim/Vim.docset/Contents/Resources/Documents/change.html#J)' flag is present in ['cpoptions'](dfile:///Users/guill/Library/Application%20Support/Dash/DocSets/Vim/Vim.docset/Contents/Resources/Documents/options.html#'cpoptions'), at least two spaces have to
follow the punctuation [mark](dfile:///Users/guill/Library/Application%20Support/Dash/DocSets/Vim/Vim.docset/Contents/Resources/Documents/motion.html#mark); <Tab>s are not recognized [as](dfile:///Users/guill/Library/Application%20Support/Dash/DocSets/Vim/Vim.docset/Contents/Resources/Documents/motion.html#as) white space.
The definition of a [sentence](dfile:///Users/guill/Library/Application%20Support/Dash/DocSets/Vim/Vim.docset/Contents/Resources/Documents/motion.html#sentence) cannot be changed.
```

paragraph boundaries are already there in kV, but not section boundaries. might take a while to implement both. what about i add the `()` but not officially yet, with just the first part of the description. would that help? i think i could get that done in a day, release, and update the motion later.

**Comment by godbout** [comment] 2022-07-30 05:18
> (Chromium but for the AX may be fixed later in 107 latest: https://bugs.chromium.org/p/chromium/issues/detail?id=1325643)

also, got in close contact with the Chromium team, and the Line Number issue is now fixed: https://bugs.chromium.org/p/chromium/issues/detail?id=1325643
so once the fix is released, we can put back Chrome and Brave in the PG-R Family and have all the kV goodies.

**Comment by godbout** [comment] 2022-07-30 09:07
`)` done. tests/rules in https://github.com/godbout/AccessibilityStrategyTestApp/blob/master/AccessibilityStrategyTestAppTests/TextObjects/Texts/FileTextTests/FT_beginningOfSentenceForward_Tests.swift and https://github.com/godbout/AccessibilityStrategyTestApp/blob/master/AccessibilityStrategyTestAppTests/AccessibilityStrategy/NormalMode/Moves/ASUT_NM_)_Tests.swift

actually i don't think not handling the `sections` is a big deal. sections are delimited by the form feed character, which i think should barely be there. let me know if i'm wrong.

**Comment by godbout** [comment] 2022-07-30 10:52
ok so as usual it ends up being way more complicated than expected. there's a difference of behavior if the caret is on an empty line (only linefeed), blank line (only spaces/tabs and linefeed), and none of the previous. so, gonna take way more time.

**Comment by godbout** [comment] 2022-07-31 09:13
added in kV30: https://github.com/godbout/kindaVim.docs/releases/tag/30

now, it's a complex move. depends whether the current location is on a text, or an empty line, or a blank line. same thing when you move to the next sentence. it should skip blank lines, but not empty lines. anyways, LOTS OF TESTING NEEDED.

done:
* here: https://github.com/godbout/AccessibilityStrategyTestApp/tree/master/AccessibilityStrategyTestAppTests/TextObjects/Texts/FileTextTests/FT_beginningOfSentenceForward_Tests
* here: https://github.com/godbout/AccessibilityStrategyTestApp/tree/master/AccessibilityStrategyTestAppTests/TextObjects/Texts/FileTextTests/FT_beginningOfSentenceBackward_Tests
* here: https://github.com/godbout/AccessibilityStrategyTestApp/blob/master/AccessibilityStrategyTestAppTests/AccessibilityStrategy/NormalMode/Moves/ASUT_NM_(_Tests.swift
* and here: https://github.com/godbout/AccessibilityStrategyTestApp/blob/master/AccessibilityStrategyTestAppTests/AccessibilityStrategy/NormalMode/Moves/ASUT_NM_)_Tests.swift

this to say: i may have missed some cases. but it's heavily tested. so if you find a case that doesn't work properly, please let me know and i'll patch it. with all the tests available, we'll keep patching and it'll keep getting better. no regression. that being said, it should already work pretty well.

if you need the count, let me know here and i'll add.
if you need the move with operators (`c`, `d`, etc.) then we open new issues. better separating, and working on them one by one.

thank you!

**Comment by bromanko** [comment] 2022-08-01 15:45
Thanks! I just installed the latest version and gave it a quick test in ia Writer. So far so good! I'll start incorporating that back in to my flow and let you know if I encounter any issues. I'll also open separate issues for missing operators that slow me down.

**Comment by godbout** [comment] 2022-08-02 07:28
please let me know yes. the point is not to break your workflow. you shouldn't have to change it. if stuff you're using are missing, we'll add them in kV. i just need to now, for the priorities of what gets worked on first. thanks!

**Closed** 2022-08-17 17:46 UTC
