### ISSUE TITLE
It is not possible to add the NeoVide App to the exception list

### ISSUE THREAD

**Issue by timseriakov** [godbout/kindaVim.docs#119] opened 2022-08-20 11:14 UTC
It is not possible to add the NeoVide App to the exception, Kinda dont see it at all.

Binded to `jj`

https://user-images.githubusercontent.com/59409712/185743417-5ac17363-81a6-4f15-9609-807a709c4270.mov

I'm using NeoVide with LunarVim.

Additional links:
https://github.com/neovide/neovide
https://github.com/LunarVim/LunarVim

**Comment by godbout** [comment] 2022-08-20 11:26
will check. can't you drag and drop the apps onto The Wizard or in the `Off` Family? if not that means they're not real apps. if they have bundle identifiers then i could hardcode them. already did something similar for some Steam link stuff.

**Comment by timseriakov** [comment] 2022-08-20 12:07
If I running `neovide` as is, it seems to be visible in `kinda`, but if I run `lunarvim` in 

https://user-images.githubusercontent.com/59409712/185745330-35255b8a-d5a3-44ab-83df-a15664004679.mov

`neovide` (custom config from another folder), `kinda` does not see it. Also, having `Neovide.app` in the `Off list` does not affect `Neovide.app` which is running with custom config. Magic outside of Hogwads...

Script to launch `Neovide` with custom config:
```sh
 export LUNARVIM_CONFIG_DIR="${LUNARVIM_CONFIG_DIR:-$HOME/.config/lvim}"
 export LUNARVIM_RUNTIME_DIR="${LUNARVIM_RUNTIME_DIR:-$HOME/.local/share/lunarvim}"
 export LUNARVIM_CACHE_DIR="${LUNARVIM_CACHE_DIR:-$HOME/.cache/lvim}"
  
 exec neovide -- -u "$LUNARVIM_RUNTIME_DIR/lvim/init.lua" "$@"

```

**Comment by godbout** [comment] 2022-08-20 16:33
it's possible that the issue is that your desktop pictures are too cool. but i'll still check.

**Comment by godbout** [comment] 2022-08-20 16:38
wtf is that shit. you can't even start it properly? need to start from the terminal? wtf. (i'm a bit drunk but still.)

**Comment by godbout** [comment] 2022-08-20 16:39
why are you guys using complicated stuff? just buy my software and send me money and life will be good.

**Comment by godbout** [comment] 2022-08-20 16:39
sorry didn't mean to close. as said above, drunk.

**Comment by godbout** [comment] 2022-08-20 16:42
can you explain to me easily how i can test this? i installed NeoVide but it stops at launch. it seems i need Neovim in my path or something? send me detailed instructions like i'm a 5 years old thanks (i'm not far. at least wisdom-wise).

**Comment by godbout** [comment] 2022-08-20 16:45
>  2022-08-20.15.00.28.mov 

i'm gonna need to find out what apps/bundle identifier are running when you're doing your magic things that we can see in the screencast. currently i have no idea how to run NeoVide and even less Lunar. (isn't this the crypto that bankrupt half of the planet???)

**Comment by godbout** [comment] 2022-08-20 16:49
ok so i installed NeoVim and NeoVide starts. it's pretty funky. the gooey cursor, i love it.

also you'll notice i tend to talk a lot.

**Comment by godbout** [comment] 2022-08-20 16:57
` lvim: command not found` oh man this is absolutely boring.

**Comment by godbout** [comment] 2022-08-20 17:00
who the fuck installs stuff inside `~/.local/bin` seriously?

**Comment by godbout** [comment] 2022-08-20 17:05
ok so i have `lvim` running from the terminal. in my case `iTerm`. so yeah you have to get `iTerm` or your terminal in the `Off` Family.

**Comment by godbout** [comment] 2022-08-20 17:07
> ```shell
>  export LUNARVIM_CONFIG_DIR="${LUNARVIM_CONFIG_DIR:-$HOME/.config/lvim}"
>  export LUNARVIM_RUNTIME_DIR="${LUNARVIM_RUNTIME_DIR:-$HOME/.local/share/lunarvim}"
>  export LUNARVIM_CACHE_DIR="${LUNARVIM_CACHE_DIR:-$HOME/.cache/lvim}"
>   
>  exec neovide -- -u "$LUNARVIM_RUNTIME_DIR/lvim/init.lua" "$@"
> ```

fucking hell why are you guys killing me with so complicated stuff?

**Comment by timseriakov** [comment] 2022-08-20 17:08
Man, I need a drink too, relax. I will write detailed instructions step by step, but a little bit later

**Comment by godbout** [comment] 2022-08-20 17:15
> I will write detailed instructions step by step, but a little bit later

by "a little bit later" you mean in three minutes right? right???

**Comment by timseriakov** [comment] 2022-08-20 17:21
As soon as I go to the store for whiskey,  come back, take a couple of sips and immediately start writing instructions. it's a damn vim-world, there's no other way

**Comment by godbout** [comment] 2022-08-20 17:24
> As soon as I go to the store for whiskey, come back, take a couple of sips and immediately start writing instructions. it's a damn vim-world, there's no other way

Glenfiddich 15 min please else i close the issue.

**Comment by godbout** [comment] 2022-08-20 17:25
can't believe the amount of shit i had to eat to get this working.

ok so if i'm not completely hammered i'm having LunarVim working in Neovide? i can add Neovide to the `Off` Family through the Menu Bar Icon (or actually through drap and drop) and things seem to work fine?

**Comment by godbout** [comment] 2022-08-20 17:27
https://user-images.githubusercontent.com/121373/185759210-ec9c0556-6bc1-4e54-b231-774e1ade9198.mp4

**Comment by godbout** [comment] 2022-08-20 17:28
> 

took me about two seconds to remember the name of my app LMFAO.

**Comment by godbout** [comment] 2022-08-20 17:31
>  2022-08-20.15.00.28.mov 

so if i get this correctly in your case you're on `Neovide` and `Neovide` is in the `Off` Family but still kV doesn't back off?

**Comment by godbout** [comment] 2022-08-20 17:38
works fine here:

https://user-images.githubusercontent.com/121373/185759553-d4489602-fd8a-4ac5-90c4-575689d426b2.mp4

maybe calling the Neovide.app/neovide from the lvim-gui?

**Comment by timseriakov** [comment] 2022-08-20 18:11
You have to admit, it was fun.

**Comment by timseriakov** [comment] 2022-08-20 18:12
> why are you guys using complicated stuff? just buy my software and send me money and life will be good.

Five minutes after reading the readme)

**Closed** 2022-08-20 18:13 UTC

**Comment by godbout** [comment] 2022-08-20 18:15
> You have to admit, it was fun.

lol. i'm not doing anything that is not fun. even burning 2.8k USD a month is fun.

**Comment by godbout** [comment] 2022-08-20 18:15
> maybe calling the Neovide.app/neovide from the lvim-gui?

so that was it? 😂️

**Comment by godbout** [comment] 2022-08-20 18:17
> Five minutes after reading the readme)

i'm surprised tho. i toned it down and remove the swear words because people said it was unprofessional but now i find it boring and i'm getting depressed ☹️

**Comment by godbout** [comment] 2022-08-20 18:17
that Neovide/LunarVim looks quite fun tho tbh 👌️

**Comment by godbout** [comment] 2022-08-20 18:18
doesn't seem i'm not going to do too much work tonight...

**Comment by timseriakov** [comment] 2022-08-20 18:21
> > Five minutes after reading the readme)
> 
> i'm surprised tho. i toned it down and remove the swear words because people said it was unprofessional but now i find it boring and i'm getting depressed ☹️

You made me a little happier this evening, that's a good thing... I rarely drink whiskey alone.

**Comment by timseriakov** [comment] 2022-08-20 18:22
And I'm also already downloading The Witness)

**Comment by godbout** [comment] 2022-08-20 18:22
> You made me a little happier this evening, that's a good thing... I rarely drink whiskey alone.

THAT"S WHAT IT"S ALL ABOUT! FUN> MEANINGFULNESS AND LOVE ❤️

**Comment by godbout** [comment] 2022-08-20 18:24
> And I'm also already downloading The Witness)

aww. you saw it in where? one of the videos? 😂️
i almost never play games. just the classics, maybe two weeks every 3/4 years? but The Witness is fucking golden. beautiful, small indie thing. a gem. have fun. try with earphones. just to hear the fucking wind going through the branches.

**Comment by timseriakov** [comment] 2022-08-20 18:28
I'm also absolutely not a player (except for the rare hardcore 15 min in `rexuiz` to feel young again). Thanks for brightening up my evening)

**Comment by godbout** [comment] 2022-08-20 18:36
my pleasure.

and lemme know how The Witness goes. i wanna hear about it.
