### ISSUE TITLE
kindaVimDidEnterNormalMode was not triggered while using custom shortcut.

### ISSUE THREAD

**Issue by xell** [godbout/kindaVim.docs#166] opened 2023-03-12 15:03 UTC
There're three methods to enter normal mode in the Settings. However, while escape and sequence can successfully send kindaVimDidEnterNormalMode Received Distributed Notifications to be captured by BetterTouchTool, custom shortcut (I've tried several keys) doesn't. But all of the three can send kindaVimDidExitNormalMode properly. The version of kindaVim is 50.

**Comment by godbout** [comment] 2023-03-12 16:03
interesting. will check. thanks.

**Comment by godbout** [comment] 2023-03-14 08:26
can confirm. thanks. will be fixed in the next release.

**Comment by godbout** [comment] 2023-03-16 07:07
@xell ok my bad, i thought it was the case but it's just that for whatever reason my Hammerspoon dialog was showing behind Xcode when i was using the custom shortcut. so here, it works. i'm gonna attach a video, and a Hammerspoon config. can you try and see on your side if Hammerspoon catches the DN? thanks.

**Comment by godbout** [comment] 2023-03-16 07:12
https://user-images.githubusercontent.com/121373/225541257-f84efb76-5b3e-46dd-8e91-57badc11d54f.mp4


the Hammerspoon config to catch that DN:

```
kVEnterNormalWatcher = hs.distributednotifications.new(function(name, object, userInfo)
    hs.notify.show("kV entered Normal Mode","","","")
end, 'kindaVimDidEnterNormalMode')
kVEnterNormalWatcher:start()
```

**Comment by xell** [comment] 2023-03-20 06:49
I tested the code in Hammperspoon 0.9.100(6815) and it works in all three modes just like your screencast showed. So it seems it's related only to BetterTouchTool?

> the Hammerspoon config to catch that DN:
> 
> ```
> kVEnterNormalWatcher = hs.distributednotifications.new(function(name, object, userInfo)
>     hs.notify.show("kV entered Normal Mode","","","")
> end, 'kindaVimDidEnterNormalMode')
> kVEnterNormalWatcher:start()
> ```

**Comment by godbout** [comment] 2023-03-20 07:49
> I tested the code in Hammperspoon 0.9.100(6815) and it worked in all three modes just like your screencast showed. So it seems it's related only to BetterTouchTool?

possible. kV sends the proper DN at the right time. can you show how you're setting up BTT? i don't use BTT myself but i can try and see what's going on. sure you don't have any mistake in the DN name etc.?

**Comment by xell** [comment] 2023-03-20 08:06
Sure. Here's the screenshot. And when I filled the input I used copy&paste from the official doc to avoid possible typos.

![CleanShot 2023-03-20 at 16 05 04@2x](https://user-images.githubusercontent.com/132558/226281001-6ad59b22-55d0-463c-80e9-df0538a8ed4b.png)

**Comment by godbout** [comment] 2023-03-20 08:08
great, thanks.

**Comment by godbout** [comment] 2023-03-20 08:26
> ok so just tried. there's options regarding modifiers that you need to set in BTT:
> 
> <img alt="Screenshot 2023-03-20 at 16 16 00" width="285" src="https://user-images.githubusercontent.com/121373/226283095-477591e0-51fa-4f83-9267-2f565a546c88.png">
> 
> once you set the proper options it will work.

honestly i don't really understand the option itself. i would have expected the trigger to work with whatever the status of the modifier keys. but it doesn't seem to be working like i thought.

**Comment by xell** [comment] 2023-03-20 08:40
> ok so just tried. there's options regarding modifiers that you need to set in BTT:
> 
> <img alt="Screenshot 2023-03-20 at 16 16 00" width="285" src="https://user-images.githubusercontent.com/121373/226283095-477591e0-51fa-4f83-9267-2f565a546c88.png">
> 
> once you set the proper options it will work.

Thank you and it works as ticking the same modifier(s) setup in the kindaVim. Now it seems not a bug rather than a feature in BTT, although hard to figure out.

**Comment by godbout** [comment] 2023-03-25 05:06
closing as this is solved. please reopen if you have any question.

**Closed by godbout** 2023-03-25 05:06 UTC

**Comment by aledoroshenko** [comment] 2024-12-14 14:54
I'm trying to do the same, but not catching any notifications. Here is my set up (Console with notification, Kindavim shortcut setup, BTT trigger setup):

![Ol35ZkOd-6KiLZpj0-9J53CLiW@2x](https://github.com/user-attachments/assets/99d2d746-ca70-4e79-99f4-ff51b54d6af6)

Any idea what i could check to debug the issue?

**Comment by godbout** [comment] 2024-12-14 15:00
> I'm trying to do the same, but not catching any notifications. Here is my set up (Console with notification, Kindavim shortcut setup, BTT trigger setup):
> 
> ![Ol35ZkOd-6KiLZpj0-9J53CLiW@2x](https://private-user-images.githubusercontent.com/981275/395790004-99d2d746-ca70-4e79-99f4-ff51b54d6af6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxODg2NTUsIm5iZiI6MTczNDE4ODM1NSwicGF0aCI6Ii85ODEyNzUvMzk1NzkwMDA0LTk5ZDJkNzQ2LWNhNzAtNGU3OS05OWY0LWZmNTFiNTRkNmFmNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNFQxNDU5MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZWZmNzJiZThiNzQ1Y2YyMzdmZWNkZjUyMGIxMDczMmNjZWM2Y2QzNmE2YjUzOTdmYWMzNTk4MDQxYTZkZDdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JWZs1_oLtuQ5lc9adGiSZgR2U3MgdTR29sssR3cwlms)
> 
> Any idea what i could check to debug the issue?

but from the console it seems that the notif are sent? so the issue is BTT doesn't grab them? am i right here? lemme know and i'll check more.

**Comment by aledoroshenko** [comment] 2024-12-14 16:04
Yep, in console i see it fine (but only `kindaVimDidEnterNormalMode`, no `kindaVimDidExitNormalMode`).

**Comment by godbout** [comment] 2024-12-14 19:52
wait. thought i was going crazy. the Distributed Notifications were deprecated many versions ago lol. how the fuck do you still receive the `EnterNormalMode` one... the code doesn't seem to have any reference to that either (will dig more tomorrow). the issue with the Distributed Notifications is that [they may sometimes be slow, and sometimes macOS doesn't even send them if it's a little overwhelmed](https://developer.apple.com/documentation/foundation/distributednotificationcenter#1770616).

so this has been replaced by a `json` file that reflects kV's Mode in real time. see: https://github.com/godbout/kindaVim.docs?tab=readme-ov-file#apis. this is what you have to check now to know kV's current Mode.

**Comment by godbout** [comment] 2024-12-14 19:57
was changed with kV59 about a year ago: https://github.com/godbout/kindaVim.docs/releases/tag/59

**Comment by godbout** [comment] 2024-12-14 20:01
> wait. thought i was going crazy. the Distributed Notifications were deprecated many versions ago lol. how the fuck do you still receive the `EnterNormalMode` one... the code doesn't seem to have any reference to that either (will dig more tomorrow). 

i'm thinking the stuff you got in the Console is from BTT, not kV. i've checked and if i'm not too dumb kV doesn't send DNs anymore.

**Comment by aledoroshenko** [comment] 2024-12-15 09:42
Got it, sorry for the confusion, will try the `json` way!

**Comment by godbout** [comment] 2024-12-15 12:38
> Got it, sorry for the confusion, will try the `json` way!

nah, my bad. i don't use the APIs coz basically i'm building kV for myself so i don't need any third party stuff 🤣️🤣️🤣️

i thought i had some more explanation somewhere about using `jq` and `watchman` etc. but can't find 🤔️ gonna have another look and update you if i find something.

**Comment by aledoroshenko** [comment] 2024-12-15 12:44
Not sure if its a good way, but I got it working with this:

```
watchman -j <<EOT
["trigger", "/Users/my_user/Library/Application Support/kindaVim/", {
  "name": "kindaVimMode",
  "expression": ["match", "environment.json"],
  "command": ["/bin/bash", "/Users/my_user/kindaVimMode.sh"],
  "stdin": ["name"]}]
EOT
```

```bash
#!/bin/bash

mode=$(jq -r .mode '/Users/my_user/Library/Application Support/kindaVim/environment.json')
/Library/Application\ Support/org.pqrs/Karabiner-Elements/bin/karabiner_cli --set-variables "{\"kindaVimMode\":\"$mode\"}"
```

**Comment by godbout** [comment] 2024-12-15 13:31
YEEEEESS. that was totally the spirit. capturing the mode from the `json` and sending it to KE through the cli. perfect. glad you got it working.

**Comment by godbout** [comment] 2024-12-15 15:18
maybe some more info there: https://github.com/godbout/kindaVim.docs/issues/201
