### ISSUE TITLE
add Notion

### ISSUE THREAD

**Issue by choco** [godbout/kindaVim.docs#89] opened 2022-06-16 07:37 UTC
Another "bad" Electron app. I'm currently using the Key mapping strategy but some motions don't seem to work well, like `gg` and `G`.

**Comment by godbout** [comment] 2022-06-16 07:44
thanks, will check. will add it to The Wizard too. i have never used Notion, so i'll do the research.

**Comment by godbout** [comment] 2022-06-16 18:37
had a quick check. the issue with the `Key Mapping` (and the whole Keyboard Strategy) is that Notion doesn't respect the macOS keyboard shortcuts standard: https://support.apple.com/en-us/HT201236

probably they override them to do their own shit. the more i deal with Electron apps (from users reports), the more it seems to me that developers of Electron stuff have some kind of delusion of greatness. they completely disregard the accessibility, they don't respect any OS keyboard shortcuts standard, or even OS UI. they just build their own world like they believe people only their own product and that's it. probably mostly care about numbers of users, and revenue.

anyways. i'll check if there's something possible with the Accessibility tomorrow. and i'll report the keyboard issue to them.

**Comment by godbout** [comment] 2022-06-17 07:48
so i've investigated why the Accessibility Strategy doesn't work. Notion returns wrong data (specifically it returns line ends longer than the full text lengths, which is impossible). for the Keyboard Strategy, as said, they override macOS keyboard shortcuts. will see how to send them a feedback, and will post here. i'll add the current situation about Notion to The Wizard for the next release (might be out today, or tomorrow, or the day after). will update once i have more info from them.

**Comment by godbout** [comment] 2022-06-17 09:04
ok, so both issues reported to the Notion team.

i'll keep this thread updated.
i know this is less than ideal, but not much we can do here. sending daily thoughts and prayers tho.

**Comment by godbout** [comment] 2022-06-17 16:57
ok after 25 emails with the support, it doesn't seem it's gonna change from their side. they like the way Notion works currently. it works "as intended".

**Comment by godbout** [comment] 2023-07-25 18:41
a year without news from Notion. closing.

**Comment by godbout** [comment] 2024-06-13 06:18
it seems it is now possible to get Notion AX Elements. will investigate.

**Comment by godbout** [comment] 2024-12-31 07:13
doesn't change anything. still needs to be put in Key Mapping Family. closing again.

**Closed by godbout** 2024-12-31 07:13 UTC
Labels: devs contacted 📧️
