### ISSUE TITLE
Support for `i` and `a` with brackets (`b([{<`) in visual mode

### ISSUE THREAD

**Issue by jannis-baum** [godbout/kindaVim.docs#101] opened 2022-07-29 10:39 UTC
> Similarly to `c`hange or `d`elete, Vim lets me select `i`n or `a`round paranthesis (`b`), `w`ords, etc in visual mode.

(This is not of high priority for me, just wanted to add it here since I saw it's not yet implemented)

## Example

Initial state in normal mode:

![initial](https://user-images.githubusercontent.com/85999315/181741314-f527f73f-9432-4916-8936-dcba23e96a13.png)

Expected state after input of `vib`:

![after vib](https://user-images.githubusercontent.com/85999315/181741485-ac133e72-6f4e-419c-8f9b-54c278a943e7.png)

**Comment by godbout** [comment] 2022-07-29 16:08
please bear with me while i'm letting you know the current status, and by the same occasion refresh my mind:

1. ok first thing, it's not really implement `i` and `a` in Visual Mode. there's many moves using `i` and `a` in Visual Mode. actually some are already implemented (`iw`, `ip`). i'm saying this because moves really do need to be implemented one by one. (for the Accessibility Strategy, Keyboard Strategy, UI and unit tests of all cases, etc. so each have to be done individually.)
2. i did work on those some weeks ago, but, as usual, it's harder and more complicated than i thought. i was working on the `vi"` one. if you check Vim:

https://user-images.githubusercontent.com/121373/181799595-3b672cb6-c557-40e9-a27e-0a086eaaecaf.mp4

my first thought was ok, we just grab what's within the `"`. but that's not the case. there's many different contexts. this is just for the `inner quote`. i'm not even showing the `a quote` which is even more nightmarish (trailing blanks? leading blanks? linefeeds? etc.). so ultimately i judged it would take a week of work focused on that, so i postponed it.

now that being said, i've experimented with `v inner bracket`, and it's easier. also the `v a bracket`. with quotes, Vim cares about trailing and leading whitespaces. but not with brackets (as far as i can recall. thoughts and prayers). so, they're on my list, and will be done quite soon. before the `.` for sure. 

will keep you posted as usual.

**Comment by godbout** [comment] 2022-07-29 16:09
ok in the video you don't see the keystrokes so it's not gonna speak to you. but if you want some nightmares have it a go before going to sleep 😂️

**Comment by xbladesub** [comment] 2022-08-02 16:39
I hope that all upcoming new cool features will not require disabling SIP 😆

**Comment by godbout** [comment] 2022-08-02 16:50
> I hope that all upcoming new cool features will not require disabling SIP 😆

never. it's deliberate. kV is you install, it's safe, and it works (although you need to put apps in some `Families` sometimes, but there's a Wizard and new apps keep being investigated and curated).

for stuff that are more hardcore with disabling SIP there's SketchyVim (see https://github.com/FelixKratz/SketchyVim/issues/12). if Felix can pull this one off, that would/could mean a Vim backend EVERYWHERE tho. so that'd be a killer. but yeah, no SIP then.

**Comment by godbout** [comment] 2022-08-06 08:06
work is starting on the `i` and `a` for opening and closing brackets `({[`.

**Comment by godbout** [comment] 2022-08-10 14:12
grossly it's there (with automated tests). but there's still some cases where i have a hard time figuring out Vim's logic 😅️

https://user-images.githubusercontent.com/121373/183922936-d45cd9c3-924e-43a0-b3ec-abed4f8a8ae7.mp4

like sometimes the motion will bip, sometimes not, and i kinda get an idea of the differences, but can't make a proper logic programmatically. i guess i need a few more days of digestion.

**Comment by godbout** [comment] 2022-08-11 14:02
ok so i thought i nailed it but, as usual with Vim, it's harder than expected. the multiline Visual Mode `iB` and co work differently when the opening and closing blocks are surrounded by linefeeds and/or blanks. it's not from opening block to end block, it's more complex than this.

https://user-images.githubusercontent.com/121373/184151053-0d3d5db0-4321-4db6-8ee6-535cb44eb16f.mp4

so this is gonna take way more time than i expected.

**Comment by godbout** [comment] 2022-08-13 04:00
so,

https://user-images.githubusercontent.com/121373/184467596-d0b1437c-9fec-4ca8-a890-96b8ed653d94.mp4

different sets of rules for `iB` and co vs `aB` and co. not just a matter of including block delimiters hahhahhahahah Vim always cracking me up.

**Comment by godbout** [comment] 2022-08-15 16:36
added in kV32: https://github.com/godbout/kindaVim.docs/releases/tag/32

it's not _perfect_, in the sense that there are a few cases that i know of and that are not covered by kV (at least for now). for example, see if you can spot the difference between:

* a context where the motion works:

https://user-images.githubusercontent.com/121373/184675855-83cb6aeb-21a8-43f1-970b-a9d10197eb51.mp4

* a context where the motion doesn't work:

https://user-images.githubusercontent.com/121373/184675864-6a865ce2-cd2e-4b2c-9a54-b7fceed084fd.mp4

well it took me two days to understand why one case works and the other doesn't. it's overly complicated (to my taste) and i think most people are not or will not be aware of those cases, so i didn't bother.

the moves have automated tests here:
* innerBlock: https://github.com/godbout/AccessibilityStrategyTestApp/blob/master/AccessibilityStrategyTestAppTests/AccessibilityStrategy/VisualMode/Helpers/ASUT_VM_innerBlock_Tests.swift
* aBlock: https://github.com/godbout/AccessibilityStrategyTestApp/blob/master/AccessibilityStrategyTestAppTests/AccessibilityStrategy/VisualMode/Helpers/ASUT_VM_aBlock_Tests.swift
* a[, aB, ab, i[, iB, ib: https://github.com/godbout/AccessibilityStrategyTestApp/tree/master/AccessibilityStrategyTestAppTests/AccessibilityStrategy/VisualMode/Moves

there's about another 50 Unit Tests i think that are in the Core and that are not open source. so that is to say, as it's quite complicated i may have missed some cases. if you find places where kV doesn't behave properly, let me know and i'll patch those. with the heavy test suite we can patch little by little without fearing any regression, and the moves will become better and better over time.

if you're ok with the results, we can close this one. 
i'm going to work on `i"`, `a'` etc. in the near future.

**Comment by jannis-baum** [comment] 2022-08-16 07:53
Looks great! This definitely covers my needs for brackets ^^ I will let you know if I notice anything else☺️

I would probably leave the issue open for the other `vi`'s and `va`'s (`:help object-select` in Vim has a nice list) but feel free to close this issue if you prefer having it focus on brackets since it is such a big topic!

**Comment by godbout** [comment] 2022-08-16 08:02
> Looks great! This definitely covers my needs for brackets ^^ I will let you know if I notice anything else☺️
> 
> I would probably leave the issue open for the other `vi`'s and `va`'s (`:help object-select` in Vim has a nice list) but feel free to change the title and close this issue if you prefer having it focus on brackets for being such a big topic!

oh, ok. in that case do you mind opening an issue for each motion? coz they take a week of work each, and it's easier for me to track. worse case i'll refer to one another within each thread. but for example this current issue is to vague, and it would take weeks before closing it and knowing "when it's done". thanks!

**Comment by jannis-baum** [comment] 2022-08-16 08:32
If that would help I wouldn't mind at all! Having all of these moves available isn't super high priority for me though so I'd only open them if you would like them for the sake of completeness. Not sure if you want issues here to be "things that people urgently want" or "the roadmap towards all Vim features". If it's the former I'll open an issue for `i`/`a` `'`, `"` and <code>`</code>, if it's the latter I can create issues for all of them. What do you think?

**Comment by godbout** [comment] 2022-08-16 09:48
> If that would help I wouldn't mind at all! Having all of these moves available isn't super high priority for me though so I'd only open them if you would like them for the sake of completeness.

there's probably 500 motions/combinations missing so i gave up on the completeness 😂️ hence kV being a lifetime project.

> Not sure if you want issues here to be "things that people urgently want" or "the roadmap towards all Vim features". If it's the former I'll open an issue for `i`/`a` `'`, `"` and `` ` ``, if it's the latter I can create issues for all of them. What do you think?

i'd say just open for your own cases. the litmus test for me is simple: i try to use a motion and it doesn't work, and i see it's not implemented. then i add it to my internal list. not "something i would like to have" or "it would be nice for completeness". but really something "hey i wanted to use that move and it's not there and i'm gonna be tricked again in the future". ultimately i want all the moves to be in kV, but realistically there has to be priorities, coz it's a lot of work :D

**Comment by jannis-baum** [comment] 2022-08-16 10:08
That makes sense! I opened #115 for quotes.

Not that it's particularly relevant to me, but my very careful guess is that `i` and `a<` might be rather quick to implement now with the other types of brackets working? If so, let's close this when they are done as well so that this issue deals with all types of brackets? If not feel free to just close this now! :)

**Comment by godbout** [comment] 2022-08-16 10:16
> Not that it's particularly relevant to me, but my very careful guess is that `i` and `a<` might be rather quick to implement now with the other types of brackets working? If so, let's close this when they are done as well so that this issue deals with all types of brackets? If not feel free to just close this now! :)

yes, i just forgot them 😅️
will add for next release. thanks!

**Comment by godbout** [comment] 2022-08-17 17:42
added in kV33: https://github.com/godbout/kindaVim.docs/releases/tag/33

**Comment by godbout** [comment] 2022-08-17 17:42
if it works, let's close.

**Closed** 2022-08-17 17:51 UTC
